### ISSUE TITLE
python environment

### ISSUE THREAD

**Issue by Wolfhan99** [mrusci/ondevice-learning-kws#1]
Hi @mrusci, thanks for your great work. I'd like to reproduce your work. But when running scripts, there will be some package version problems.  Could you provide requirements.txt file that including the version of torch, torchaudio and something else required in this project?

**Comment by mrusci** [comment]
thanks for your comment and apology for my late reply.
I will push soon a requirements file (I need to clean my pip list). In the meantime, I can write here the version of the main Python packages. just let me know if you need any clarification on specific module. 

`librosa              0.9.2 `
`numpy                1.21.6 `
`scikit-learn         1.0.2 `
`scipy                1.7.3 `
`soundfile            0.11.0 `
`torch                1.12.1 `
`torchaudio           0.12.1 `
