### ISSUE TITLE
Add specific version of used dataset

### ISSUE THREAD

**Issue by matteorisso** [mrusci/ondevice-learning-kws#2]
First of all, thank you for the nice work and for open-sourcing it.

I'm opening this issue to suggest you to indicate in the README the specific version of the HeySnips dataset to be used given that two different versions exist.

In particular, when using the first version, i.e., the one associated to _Coucke et al., 2019, "Efficient keyword spotting using dilated convolutions and gating"_ an error is raised in the `self_learning_personalized_kws.py` script at line 184 due to the fact that the minimum number of positive samples is <= 10.

Best,
Matteo

**Comment by mrusci** [comment]
Thanks for noticing. The correct version is the V2. I updated the README and I will point this out also in an updated paper version. I hope you were able to reproduce the paper results using the data.
